# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 4 * * 1,4" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: nostam
          template: classic
          base: ""
          config_timezone: Europe/Amsterdam
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage   
          plugin_languages_threshold: 0%
